### ISSUE TITLE
Introduce a TS SDK testing standard and approach

### ISSUE THREAD

**Issue by danielbate** [FuelLabs/fuels-ts#1043]
As we approach mainnet, it is important we start to implement some stricter testing standards that ensures parity with the protocol/FuelVM and gives us the greatest level of confidence in the changes we are making as uptake in the SDK increases. Additionally, we can consolidate and structure our testing to give greater clarity as to what behaviours we are currently supporting. I would like to propose some MoSCoW testing standards as well as a roadmap of changes to bring the current SDK in line with the standards.

### Where we are now
- Most functions, classes and modules have a related test file that contains a mix of unit and feature tests
- Each package approaches testing slightly differently
- Each test case is using different language and syntax
- Some packages are separating unit and feature tests into separate directories
- Heavy reliance on `fuel-gauge` for feature and integration level testing
- Some integration testing is done within the documentation directories
- Ad-hoc creation of `forc` projects for tests

### Proposed standards
- Functions, classes and modules must have a supporting unit test file
- Unit tests must verify all behaviours and correctness of functions, classes and modules
- Unit tests must mock any applicable functions, classes or modules that are not the service under test
- Unit tests must have 100% coverage of the service under test
- Packages should have a test directory
- Package test directories should contain fixtures and test data to be shared across tests within the package
- Package test directories could contain mocks and stubs of functions, classes and modules
- Package test directories should contain appropriate feature tests
- Feature tests must simulate real word interactions to validate the behaviour of a packages features from the perspective of an SDK consumer
- Integration tests should be used to demonstrate the interoperability of packages to deliver key behaviours to the SDK consumer
- Test Driven Development (TDD) could be used to identify, isolate and resolve erroneous behaviours and to implement bug fixes
- Shared test helpers and utilities should live within the `utils` packages
- Test cases should follow the gherkin syntax (e.g. `Given X, When Y, Then Z` - for unit tests only `when` and `then` are usually required as the `given` is our service under test. We can then utilise the `it()` syntax for unit tests and `test()` syntax for feature and integration tests)
- CI pipeline should enforce a coverage prerequisite to push to `master`

### Tasks (TBD)
- [ ] Document the test standards and approach within the SDK
- [ ] Refactor each package to contain a feature test directory
- [ ] Add test coverage check to CI pipeline

This should bring greater clarity to the behaviours supported by the SDK, give greater confidence in the quality of our tests and increase overall coverage as discussed in #753 . All standards and tasks are up for discussion and I would appreciate any insights 😃

**Comment by arboleya** [comment]
Here's how these tests could be spread in directories:

```yaml
<package-name>
├── src
│   ├── index.test.ts # This would be a unit
│   └── index.ts
└── test
    ├── e2e
    ├── feature
    ├── fixtures
    ├── integration
    └── utils
```

I ended up with [`test/{fixtures,utils,feature}`](https://github.com/FuelLabs/fuels-ts/tree/aa/feat/fuels-cli/packages/fuels/test) in:
 - #1291

It worked great, and I think all packages should segregate their tests.

This goes back to maybe re-distributing all tests from inside `fuel-gauge` to other packages, and although something like this might not work _(because these tests must import from `fuels`)_:
 - `packages/contract/test/integration/multicall.test.ts`

One thing that could work is:
 - `packages/fuels/test/integration/multicall.test.ts`
