### ISSUE TITLE
Encoding / Decoding revamp

### ISSUE THREAD

**Issue by arboleya** [FuelLabs/fuels-ts#1672]
The Sway compiler is going through a long-discussed revamp of its encoder/decoder scheme, eventually leading to an intermediary representation that both the SDK and the compiler will target.

This will act as a topic issue to encompass everything necessary:

Must have:
 - [x] https://github.com/FuelLabs/fuels-ts/issues/1671
 - [x] https://github.com/FuelLabs/fuels-ts/issues/1739
 - [x] https://github.com/FuelLabs/fuels-ts/issues/1749

----

Issues from other repos:
 - Specs: https://github.com/FuelLabs/fuel-specs/pull/541
 - Sway: https://github.com/FuelLabs/sway/issues/4769
 - Rust SDK: https://github.com/FuelLabs/fuels-rs/issues/1246

----

Desirable items will be addressed as follow-ups:
 - https://github.com/FuelLabs/fuels-ts/issues/1187
 - Configurable constants (currently [unsupported](https://github.com/FuelLabs/sway/issues/5727) in sway)
 - Introduce config driven coding and reduce touch points - #1795 
 - Functional rewrite for `abi-coder` - #1795 
 - Merge the `forc-project` directories - #2005

**Comment by danielbate** [comment]
The process I am using for this work is as follows:

- [ ] Introduce `v1` decode, two version support and encode `RawSlice` as `u8` - #1673 
- [ ] Introduce `v1` encode and multiple version support
- [ ] Support in contracts for #1739 
- [ ] Support in scripts and predicates for #1749
- [ ] Reduce coder touch points and be more config driven
- [ ] Introduce width checking for #1187

**Comment by arboleya** [comment]
Yes, we can. The desired items can be follow-ups.
