### ISSUE TITLE
Fix issues with flaky tests

### ISSUE THREAD

**Issue by arboleya** [FuelLabs/fuels-ts#1755]
We have a number of flakey tests in CI. The source of which seems to be the shared `fuel-core` node across test suites. Given we have merged https://github.com/FuelLabs/fuels-ts/pull/2378 we can now integrate `launchTestNode` across our testing infrastructure, then we review the flakey tests. 

E.g. I've seen this one a couple of times now:
https://github.com/FuelLabs/fuels-ts/actions/runs/7914766231/job/21605183065#step:9:505

```
⎯⎯⎯⎯⎯⎯⎯ Failed Tests 1 ⎯⎯⎯⎯⎯⎯⎯

 FAIL  packages/fuel-gauge/src/predicate/predicate-with-contract.test.ts > Predicate > With Contract > calls a predicate and uses proceeds for a contract call
Error: Expected value: '1299797' to be within range: '1300778-1300818'
 ❯ Module.expectToBeInRange packages/utils/src/test-utils/getForcProject.ts:118:9
     76|     inputGlobal,
     77|   };
     78| };
       |             ^
     79| 
 ❯ packages/fuel-gauge/src/predicate/predicate-with-contract.test.ts:149:7
```

Here's the list of issues related to the integration of `launchTestNode` across our suites:

- [ ] https://github.com/FuelLabs/fuels-ts/issues/1820
- [ ] https://github.com/FuelLabs/fuels-ts/issues/2081
- [ ] https://github.com/FuelLabs/fuels-ts/issues/2744
- [ ] https://github.com/FuelLabs/fuels-ts/issues/2698

**Comment by arboleya** [comment]
Three more in the same run:
https://github.com/FuelLabs/fuels-ts/actions/runs/7920711419/job/21624341501?pr=1759#step:9:597

```
 FAIL  packages/account/src/providers/memory-cache.test.ts > Memory Cache > can get active [with data]
AssertionError: expected [ '0xa82b33dd9ae34fd0' ] to strictly equal [ '0xa82b33dd9ae34fd0', …(2) ]
```

```
 FAIL  packages/account/src/providers/memory-cache.test.ts > Memory Cache > can get all [with data + expired data]
AssertionError: expected [ '0xa82b33dd9ae34fd0', …(1) ] to strictly equal [ '0xa82b33dd9ae34fd0', …(3) ]
```

```
 FAIL  packages/fuel-gauge/src/predicate/predicate-with-contract.test.ts > Predicate > With Contract > calls a predicate and uses proceeds for a contract call
Error: Expected value: '1299797' to be within range: '1300778-1300818'
```

**Comment by arboleya** [comment]
Again, and again.
https://github.com/FuelLabs/fuels-ts/actions/runs/8001998696/job/21854332907?pr=1788#step:9:125

```
FAIL  packages/account/src/providers/memory-cache.test.ts > Memory Cache > can get active [with data]
AssertionError: expected [ '0xe3f854f2d6d563b8', …(1) ] to strictly equal [ '0xe3f854f2d6d563b8', …(2) ]
```

```
FAIL  packages/account/src/providers/memory-cache.test.ts > Memory Cache > can get all [with data + expired data]
AssertionError: expected [ '0xe3f854f2d6d563b8', …(2) ] to strictly equal [ '0xe3f854f2d6d563b8', …(3) ]
```

**Comment by arboleya** [comment]
One more time:
https://github.com/FuelLabs/fuels-ts/actions/runs/8002556292/job/21856024641?pr=1789

```
 FAIL  packages/fuel-gauge/src/predicate/predicate-evaluations.test.ts > Predicate > Evaluations > calls a no argument predicate and returns true
Error: Validity(InsufficientFeeAmount { expected: 213, provided: 128 }): {"response":{"data":null,"errors":[{"message":"Validity(InsufficientFeeAmount { expected: 213, provided: 128 })","locations":[{"line":2,"column":3}],"path":["submit"]}],"status":200,"headers":{}},"request":{"query":"mutation submit($encodedTransaction: HexString!) {\n  submit(tx: $encodedTransaction) {\n    id\n  }\n}","variables":{"encodedTransaction":"0x000000000000000000000000000027100000000000000004000000000000000000000000000000010000000000000002000000000000000200000000000000010000000000000000000000000000000000000000000000000000000000000000240000000000000000000000000000010000000000000000e2dfb233ae4c38757a2080a4ea0353b02943e31dc25f33ca7f7b6053c61772c10000000000000001d19a5fe4cb9baf41ad9813f1a6fef551107c8e8e3f499a6e32bccbb954a747640000000000000064000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000013000000000000003400000000000000007400000347000000000000000000002c5dfcc00110fff3001aec5000910000005c43f00024400000470000000100000000000000000000000000000000000000575f5b043f4e9e7966c9fee5ed043010a3d0f4dc11552885bee50594d00970f80000000000000001d19a5fe4cb9baf41ad9813f1a6fef551107c8e8e3f499a6e32bccbb954a74764000000000000001c000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000013000000000000003400000000000000007400000347000000000000000000002c5dfcc00110fff3001aec5000910000005c43f000244000004700000001000000000000000000000000000000000000003179123b1c8446cd6d30f607726309ff685194186a948102bbbd220ca9e798c4000000000000003200000000000000000000000000000000000000000000000000000000000000000000000000000002d19a5fe4cb9baf41ad9813f1a6fef551107c8e8e3f499a6e32bccbb954a7476400000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"}}}
```

**Comment by arboleya** [comment]
Here we go again:
https://github.com/FuelLabs/fuels-ts/actions/runs/8002871668/job/21857013841?pr=1790

```
FAIL  packages/account/src/providers/memory-cache.test.ts > Memory Cache > can get active [with data]
AssertionError: expected [ '0x7ab461586a7e9b8a' ] to strictly equal [ '0x7ab461586a7e9b8a', …(2) ]
```

```
FAIL  packages/account/src/providers/memory-cache.test.ts > Memory Cache > can get all [with data + expired data]
AssertionError: expected [ '0x7ab461586a7e9b8a', …(1) ] to strictly equal [ '0x7ab461586a7e9b8a', …(3) ]
```

**Comment by arboleya** [comment]
https://github.com/FuelLabs/fuels-ts/actions/runs/8002556292/job/21858435060?pr=1789

```
FAIL  packages/fuel-gauge/src/policies.test.ts > Policies > should ensure TX policies are properly set (ScriptTransactionRequest)
Error: Validity(TransactionMaturity): {"response":{"data":null,"errors":[{"message":"Validity(TransactionMaturity)","locations":[{"line":2,"column":3}],"path":["submit"]}],"status":200,"headers":{}},"request":{"query":"mutation submit($encodedTransaction: HexString!) {\n  submit(tx: $encodedTransaction) {\n    id\n  }\n}","variables":{"encodedTransaction":"0x0000000000000000000000000000000d00000000000000040000000000000000000000000000000f0000000000000001000000000000000200000000000000010000000000000000000000000000000000000000000000000000000000000000240000000000000000000000000000020000000000000345000000000000000200000000000024b1000000000000000018c01c262530830dc4f9f14c05c130a47926eb560da1721f44dbed385a1c9caa0000000000000001fd40d01[533](https://github.com/FuelLabs/fuels-ts/actions/runs/8002556292/job/21858435060?pr=1789#step:9:534)047bd71716c66c8547f7cdb6af1b466118c03a4c5a67da3a274309000000000007a120000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000dd96f2b11f7beeeddd9d33814201ab01f7099a86ceb5463c88f9e9f075636f1100000000000001f400000000000000000000000000000000000000000000000000000000000000000000000000000002fd40d01533047bd71716c66c8547f7cdb6af1b466118c03a4c5a67da3a274309000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000040f7e97892eb4d0c659f9c2716692854bda602b15276e44a707f96945bd820546045d9593b5dd76a310540ae5be16c3ff2605bb483a220cc12ac8dc754fcfff7a8"}}}
```

**Comment by danielbate** [comment]
Would be interesting to see if we can prove these working with #1356 where parallel txs wouldn't be an issue.

**Comment by petertonysmith94** [comment]
https://github.com/FuelLabs/fuels-ts/actions/runs/8230682592/job/22504434996?pr=1846#step:9:207
```
packages/fuel-gauge/src/transaction-response.test.ts > TransactionResponse > should throw error for a SqueezedOut status update [submitAndAwait]
Test timed out in 7000ms.
```

**Comment by maschad** [comment]
Another one https://github.com/FuelLabs/fuels-ts/actions/runs/8615957986/job/23628036102?pr=2030#step:9:620

**Comment by arboleya** [comment]
@nedsalk Regarding the above [error](https://github.com/FuelLabs/fuels-ts/issues/1755#issuecomment-2046080940) — is it related to the stream parsing logic?

@Torres-ssf Is this the same stream issue you mentioned you had?

**Comment by Torres-ssf** [comment]
The same error happens here as well:
https://github.com/FuelLabs/fuels-ts/actions/runs/8601001563/job/23567196292#step:9:807

```
 FAIL  packages/fuel-gauge/src/raw-slice.test.ts > Raw Slice Tests > should test raw slice input [predicate-raw-slice]
FuelError: Error while parsing stream data response: data:{"data":{"statusChange":{"type":"SubmittedStatus","time":"4611686020139971391"}}}

data:{"data":{"statusChange":{"type":"SuccessStatus","block":
...
```

**Comment by maschad** [comment]
Also https://github.com/FuelLabs/fuels-ts/actions/runs/8878299585/job/24373658684#step:10:699

**Comment by maschad** [comment]
As well as https://github.com/FuelLabs/fuels-ts/actions/runs/8880413928/job/24380375347?pr=2199#step:10:709

```console
 FAIL  packages/fuel-gauge/src/transaction-response.test.ts > TransactionResponse > should throw error for a SqueezedOut status update [submitAndAwait]
Error: Passed-in lambda didn't throw.
 ❯ Module.expectToThrowFuelError packages/errors/src/test-utils/safeExec.ts:101:11
     12| 
     13|   return { error, result };
     14| };
       |             ^
     15| 
```

**Comment by maschad** [comment]
I'm unassigning myself as these seem far less frequent [post-upgrade](https://github.com/FuelLabs/fuels-ts/pull/2217)

**Comment by arboleya** [comment]
https://github.com/FuelLabs/fuels-ts/actions/runs/9157236096/job/25173194256?pr=2332#step:5:635

```
⎯⎯⎯⎯⎯⎯⎯ Failed Tests 1 ⎯⎯⎯⎯⎯⎯⎯

 FAIL  packages/fuel-gauge/src/predicate/predicate-with-contract.test.ts > Predicate > With Contract > executes a contract call with a predicate to ensure not extra witnesses are added
FuelError: Transaction is not inserted. UTXO does not exist: 0xc39d40bd57088ba677d7e01162bc1c220a2e1a75ee64ef62d4b2138e20d996610000
```

**Comment by arboleya** [comment]
> [!NOTE]
> Re-check this issue after this lands:
> - https://github.com/FuelLabs/fuels-ts/issues/1820

**Comment by petertonysmith94** [comment]
- https://github.com/FuelLabs/fuels-ts/actions/runs/9898356515/job/27358845148?pr=2757#step:5:961

cc @nedsalk 

```console
FAIL  packages/account/src/test-utils/launchNode-singular-test.test.ts > launchNode-singular-test > synchronous cleanup kills node before test runner exits
AssertionError: promise resolved "Response{ [Symbol(realm)]: null, …(2) }" instead of rejecting

- Expected
+ Received

- [Error: rejected promise]
+ Response {
+   Symbol(realm): null,
+   Symbol(state): Object {
+     "aborted": false,
+     "body": Object {
+       "stream": ReadableStream {
+         Symbol(kType): "ReadableStream",
+         Symbol(kState): Object {
+           "controller": ReadableStreamDefaultController {
+             Symbol(kType): "ReadableStreamDefaultController",
+             Symbol(kState): Object {
+               "cancelAlgorithm": [Function bound cancel],
+               "closeRequested": false,
+               "highWaterMark": 0,
+               "pullAgain": false,
+               "pullAlgorithm": [Function bound pull],
+               "pulling": false,
+               "queue": Array [],
+               "queueTotalSize": 0,
+               "sizeAlgorithm": [Function size],
+               "started": true,
+               "stream": ReadableStream {
+                 Symbol(kType): "ReadableStream",
+                 Symbol(kState): [Circular],
+                 Symbol(nodejs.webstream.isClosedPromise): Object {
+                   "promise": Promise {},
+                   "reject": [Function anonymous],
+                   "resolve": [Function anonymous],
+                 },
+                 Symbol(nodejs.webstream.controllerErrorFunction): [Function bound error],
+               },
+             },
+           },
+           "disturbed": false,
+           "reader": undefined,
+           "state": "readable",
+           "storedError": undefined,
+           "stream": undefined,
+           "transfer": Object {
+             "port1": undefined,
+             "port2": undefined,
+             "promise": undefined,
+             "writable": undefined,
+           },
+         },
+         Symbol(nodejs.webstream.isClosedPromise): Object {
+           "promise": Promise {},
+           "reject": [Function anonymous],
+           "resolve": [Function anonymous],
+         },
+         Symbol(nodejs.webstream.controllerErrorFunction): [Function bound error],
+       },
+     },
+     "cacheState": "",
+     "headersList": HeadersList {
+       "cookies": null,
+       Symbol(headers map): Map {
+         "access-control-allow-origin" => Object {
+           "name": "access-control-allow-origin",
+           "value": "*",
+         },
+         "access-control-allow-methods" => Object {
+           "name": "access-control-allow-methods",
+           "value": "*",
+         },
+         "access-control-allow-headers" => Object {
+           "name": "access-control-allow-headers",
+           "value": "*",
+         },
+         "content-length" => Object {
+           "name": "content-length",
+           "value": "0",
+         },
+         "date" => Object {
+           "name": "date",
+           "value": "Fri, 12 Jul 2024 06:25:43 GMT",
+         },
+       },
+       Symbol(headers map sorted): null,
+     },
+     "rangeRequested": false,
+     "requestIncludesCredentials": true,
+     "status": 405,
+     "statusText": "Method Not Allowed",
+     "timingAllowPassed": true,
+     "timingInfo": Object {
+       "decodedBodySize": 0,
+       "encodedBodySize": 0,
+       "endTime": 0,
+       "finalConnectionTimingInfo": null,
+       "finalNetworkRequestStartTime": 0,
+       "finalNetworkResponseStartTime": 0,
+       "finalServiceWorkerStartTime": 0,
+       "postRedirectStartTime": 135863.21586599[998](https://github.com/FuelLabs/fuels-ts/actions/runs/9898356515/job/27358845148?pr=2757#step:5:1012),
+       "redirectEndTime": 0,
+       "redirectStartTime": 0,
+       "startTime": 135863.215865[999](https://github.com/FuelLabs/fuels-ts/actions/runs/9898356515/job/27358845148?pr=2757#step:5:1013)98,
+     },
+     "type": "basic",
+     "urlList": Array [
+       "http://0.0.0.0:4002/v1/graphql",
+     ],
+   },
+   Symbol(headers): Headers {
+     Symbol(guard): "immutable",
+     Symbol(headers list): HeadersList {
+       "cookies": null,
+       Symbol(headers map): Map {
+         "access-control-allow-origin" => Object {
+           "name": "access-control-allow-origin",
+           "value": "*",
+         },
+         "access-control-allow-methods" => Object {
+           "name": "access-control-allow-methods",
+           "value": "*",
+         },
+         "access-control-allow-headers" => Object {
+           "name": "access-control-allow-headers",
+           "value": "*",
+         },
+         "content-length" => Object {
+           "name": "content-length",
+           "value": "0",
+         },
+         "date" => Object {
+           "name": "date",
+           "value": "Fri, 12 Jul 2024 06:25:43 GMT",
+         },
+       },
+       Symbol(headers map sorted): null,
+     },
+     Symbol(realm): null,
+   },
+ }
```

**Comment by arboleya** [comment]
This `MemoryStore` [error](https://github.com/FuelLabs/fuels-ts/issues/1755#issuecomment-2218087557) happened again:

 - `packages/fuel-gauge/src/await-execution.test.ts`
   - https://github.com/FuelLabs/fuels-ts/actions/runs/10028593195/job/27715702003#step:5:906

```
⎯⎯⎯⎯⎯⎯⎯ Failed Tests 1 ⎯⎯⎯⎯⎯⎯⎯

 FAIL  packages/fuel-gauge/src/await-execution.test.ts > await-execution > awaiting execution of a transaction on the provider works
FuelError: got error during work with storage The historical view is not implemented for `MemoryStore`
 ❯ responseMiddleware packages/account/src/wallet/base-wallet-unlocked.ts:3951:19
    158|     return encryptKeystoreWallet(this.privateKey, this.address, passwo…
    159|   }
    160| }
       |  ^
    161| 
 ❯ node_modules/.pnpm/graphql-request@5.0.0_graphql@16.9.0/node_modules/graphql-request/src/index.ts:345:11
 ❯ _Provider.estimateTxDependencies packages/account/src/wallet/base-wallet-unlocked.ts:4170:11
 ❯ _Provider.getTransactionCost packages/account/src/wallet/base-wallet-unlocked.ts:4411:74
 ❯ WalletUnlocked.estimateAndFundTransaction packages/account/src/wallet/base-wallet-unlocked.ts:5575:20
 ❯ WalletUnlocked.createTransfer packages/account/src/wallet/base-wallet-unlocked.ts:5342:15
 ❯ packages/fuel-gauge/src/await-execution.test.ts:23:22

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
Serialized Error: { VERSIONS: { FORC: '0.62.0', FUEL_CORE: '0.31.0', FUELS: '0.92.1' }, metadata: {}, rawError: {}, code: 'invalid-request', toObject: 'Function<toObject>' }
```

**Comment by petertonysmith94** [comment]
> This `MemoryStore` [error](https://github.com/FuelLabs/fuels-ts/issues/1755#issuecomment-2218087557) happened again:

Ditto:
- https://github.com/FuelLabs/fuels-ts/actions/runs/10035937705/job/27735081400?pr=2796#step:5:1297

**Comment by arboleya** [comment]
Closing this before it grows legs and starts chasing ways.

Seriously tho, it's time for a new flaky season:
 - https://github.com/FuelLabs/fuels-ts/issues/2967
