### ISSUE TITLE
Revamp `create fuels` example dApp

### ISSUE THREAD

**Issue by maschad** [FuelLabs/fuels-ts#2468]
This is an epic to track the reformation of the `create fuels` example dApp.

- ~[x] https://github.com/FuelLabs/fuels-ts/issues/2459~
- ~[x] https://github.com/FuelLabs/fuels-ts/issues/2460~
- [x] https://github.com/FuelLabs/fuels-ts/issues/2508
- [x] https://github.com/FuelLabs/fuels-ts/issues/2461
- [x] https://github.com/FuelLabs/fuels-ts/issues/2463
- [x] https://github.com/FuelLabs/fuels-ts/issues/2464
- [x] https://github.com/FuelLabs/fuels-ts/issues/2465
